Using selector: EpollSelector
Watching for file changes with StatReloader
Got 3 posts
User valakas checked the main page
Created a comment on post 3 from user valakas
/home/codio/workspace/blango/blango/settings.py changed, reloading.
Watching for file changes with StatReloader
User valakas checked the main page
Created a comment on post 2 from user valakas
Watching for file changes with StatReloader
User AnonymousUser checked the main page
User valakas checked the main page
Not Found: /favicon.ico
Created a comment on post 2 from user valakas
/home/codio/workspace/blango/blango/settings.py changed, reloading.
INFO 2023-08-01 19:37:00,974 autoreload 226 139737501275968 Watching for file changes with StatReloader
INFO 2023-08-01 19:37:25,657 autoreload 226 139737501275968 /home/codio/workspace/blango/blango/settings.py changed, reloading.
INFO 01  autoreload 229 140164416272192 Watching for file changes with StatReloader
INFO 01  autoreload 229 140164416272192 /home/codio/workspace/blango/blango/settings.py changed, reloading.
INFO 01 08 23 autoreload 232 139864802862912 Watching for file changes with StatReloader
INFO 01 08 23 autoreload 232 139864802862912 /home/codio/workspace/blango/blango/settings.py changed, reloading.
INFO 01 08 23 autoreload 235 139776343803712 Watching for file changes with StatReloader
INFO 01 08 23 autoreload 235 139776343803712 /home/codio/workspace/blango/blango/settings.py changed, reloading.
INFO 01.08.23 autoreload 238 140172229879616 Watching for file changes with StatReloader
INFO 01.08.23 autoreload 238 140172229879616 /home/codio/workspace/blango/blango/settings.py changed, reloading.
INFO 01.08.23 autoreload 241 139630093604672 Watching for file changes with StatReloader
INFO 01.08.23 autoreload 241 139630093604672 /home/codio/workspace/blango/blango/settings.py changed, reloading.
INFO 01/08.23 autoreload 244 140568160294720 Watching for file changes with StatReloader
INFO 01/08.23 autoreload 244 140568160294720 /home/codio/workspace/blango/blango/settings.py changed, reloading.
INFO 01/08/23 19:38 autoreload 247 140588256442176 Watching for file changes with StatReloader
INFO 01/08/23 19:38 views 247 140588144846592 User valakas checked the main page
INFO 01/08/23 19:39 views 247 140588144846592 Created a comment on post 3 from user valakas
INFO 01/08/23 19:40 autoreload 247 140588256442176 /home/codio/workspace/blango/blango/settings.py changed, reloading.
INFO 01/08/23 19:40 autoreload 256 140505948989248 Watching for file changes with StatReloader
INFO 01/08/23 19:40 views 256 140505837655808 Created a comment on post 3 from user valakas
INFO 01/08/23 19:46 autoreload 256 140505948989248 /home/codio/workspace/blango/blango/settings.py changed, reloading.
INFO 01/08/23 19:46 autoreload 265 140158363641664 Watching for file changes with StatReloader
INFO 01/08/23 19:48 autoreload 271 139767732774720 Watching for file changes with StatReloader
INFO 01/08/23 19:57 autoreload 346 140617370490688 Watching for file changes with StatReloader
INFO 03/08/23 21:11 autoreload 636 140216433960768 Watching for file changes with StatReloader
INFO 03/08/23 21:11 views 636 140216253806336 User AnonymousUser checked the main page
INFO 03/08/23 21:11 views 636 140216253806336 User AnonymousUser checked the main page
INFO 09/08/23 21:23 autoreload 379 139860093679424 Watching for file changes with StatReloader
INFO 09/08/23 21:24 autoreload 384 140476357523264 Watching for file changes with StatReloader
INFO 09/08/23 21:34 autoreload 384 140476357523264 /home/codio/workspace/blango/blog/views.py changed, reloading.
INFO 09/08/23 21:34 autoreload 459 140167057729344 Watching for file changes with StatReloader
INFO 09/08/23 21:34 autoreload 459 140167057729344 /home/codio/workspace/blango/blog/views.py changed, reloading.
INFO 09/08/23 21:34 autoreload 467 139953897584448 Watching for file changes with StatReloader
INFO 09/08/23 21:35 autoreload 467 139953897584448 /home/codio/workspace/blango/blog/views.py changed, reloading.
INFO 09/08/23 21:35 autoreload 470 139637520516928 Watching for file changes with StatReloader
INFO 09/08/23 21:40 autoreload 574 139738695849792 Watching for file changes with StatReloader
INFO 09/08/23 21:41 autoreload 656 139867964651328 Watching for file changes with StatReloader
INFO 09/08/23 21:46 autoreload 743 140037819770688 Watching for file changes with StatReloader
INFO 10/08/23 08:12 autoreload 238 140445982992192 Watching for file changes with StatReloader
INFO 10/08/23 08:15 autoreload 245 139706701801280 Watching for file changes with StatReloader
ERROR 10/08/23 08:15 log 245 139706590205696 Internal Server Error: /post/my-example-post
Traceback (most recent call last):
  File "/home/codio/.local/lib/python3.6/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/codio/.local/lib/python3.6/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/codio/workspace/blango/blog/views.py", line 35, in post_detail
    "comment_form": comment_form})
  File "/home/codio/.local/lib/python3.6/site-packages/django/shortcuts.py", line 19, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/home/codio/.local/lib/python3.6/site-packages/django/template/loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "/home/codio/.local/lib/python3.6/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/home/codio/.local/lib/python3.6/site-packages/django/template/base.py", line 170, in render
    return self._render(context)
  File "/home/codio/.local/lib/python3.6/site-packages/django/template/base.py", line 162, in _render
    return self.nodelist.render(context)
  File "/home/codio/.local/lib/python3.6/site-packages/django/template/base.py", line 938, in render
    bit = node.render_annotated(context)
  File "/home/codio/.local/lib/python3.6/site-packages/django/template/base.py", line 905, in render_annotated
    return self.render(context)
  File "/home/codio/.local/lib/python3.6/site-packages/django/template/loader_tags.py", line 150, in render
    return compiled_parent._render(context)
  File "/home/codio/.local/lib/python3.6/site-packages/django/template/base.py", line 162, in _render
    return self.nodelist.render(context)
  File "/home/codio/.local/lib/python3.6/site-packages/django/template/base.py", line 938, in render
    bit = node.render_annotated(context)
  File "/home/codio/.local/lib/python3.6/site-packages/django/template/base.py", line 905, in render_annotated
    return self.render(context)
  File "/home/codio/.local/lib/python3.6/site-packages/django/template/loader_tags.py", line 62, in render
    result = block.nodelist.render(context)
  File "/home/codio/.local/lib/python3.6/site-packages/django/template/base.py", line 938, in render
    bit = node.render_annotated(context)
  File "/home/codio/.local/lib/python3.6/site-packages/django/template/base.py", line 905, in render_annotated
    return self.render(context)
  File "/home/codio/.local/lib/python3.6/site-packages/django/templatetags/cache.py", line 47, in render
    value = self.nodelist.render(context)
  File "/home/codio/.local/lib/python3.6/site-packages/django/template/base.py", line 938, in render
    bit = node.render_annotated(context)
  File "/home/codio/.local/lib/python3.6/site-packages/django/template/base.py", line 905, in render_annotated
    return self.render(context)
  File "/home/codio/.local/lib/python3.6/site-packages/django/template/library.py", line 214, in render
    _dict = self.func(*resolved_args, **resolved_kwargs)
  File "/home/codio/workspace/blango/blog/templatetags/blog_extras.py", line 55, in recent_posts
    posts = cache.get_or_set(f"recent_posts_exclude_post_{post.pk}", get_recent_post(post))
NameError: name 'cache' is not defined
ERROR 10/08/23 08:32 log 245 139706590205696 Internal Server Error: /post/how-to-earn-while-playing-games
Traceback (most recent call last):
  File "/home/codio/.local/lib/python3.6/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/codio/.local/lib/python3.6/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/codio/workspace/blango/blog/views.py", line 35, in post_detail
    "comment_form": comment_form})
  File "/home/codio/.local/lib/python3.6/site-packages/django/shortcuts.py", line 19, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/home/codio/.local/lib/python3.6/site-packages/django/template/loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "/home/codio/.local/lib/python3.6/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/home/codio/.local/lib/python3.6/site-packages/django/template/base.py", line 170, in render
    return self._render(context)
  File "/home/codio/.local/lib/python3.6/site-packages/django/template/base.py", line 162, in _render
    return self.nodelist.render(context)
  File "/home/codio/.local/lib/python3.6/site-packages/django/template/base.py", line 938, in render
    bit = node.render_annotated(context)
  File "/home/codio/.local/lib/python3.6/site-packages/django/template/base.py", line 905, in render_annotated
    return self.render(context)
  File "/home/codio/.local/lib/python3.6/site-packages/django/template/loader_tags.py", line 150, in render
    return compiled_parent._render(context)
  File "/home/codio/.local/lib/python3.6/site-packages/django/template/base.py", line 162, in _render
    return self.nodelist.render(context)
  File "/home/codio/.local/lib/python3.6/site-packages/django/template/base.py", line 938, in render
    bit = node.render_annotated(context)
  File "/home/codio/.local/lib/python3.6/site-packages/django/template/base.py", line 905, in render_annotated
    return self.render(context)
  File "/home/codio/.local/lib/python3.6/site-packages/django/template/loader_tags.py", line 62, in render
    result = block.nodelist.render(context)
  File "/home/codio/.local/lib/python3.6/site-packages/django/template/base.py", line 938, in render
    bit = node.render_annotated(context)
  File "/home/codio/.local/lib/python3.6/site-packages/django/template/base.py", line 905, in render_annotated
    return self.render(context)
  File "/home/codio/.local/lib/python3.6/site-packages/django/templatetags/cache.py", line 47, in render
    value = self.nodelist.render(context)
  File "/home/codio/.local/lib/python3.6/site-packages/django/template/base.py", line 938, in render
    bit = node.render_annotated(context)
  File "/home/codio/.local/lib/python3.6/site-packages/django/template/base.py", line 905, in render_annotated
    return self.render(context)
  File "/home/codio/.local/lib/python3.6/site-packages/django/template/library.py", line 214, in render
    _dict = self.func(*resolved_args, **resolved_kwargs)
  File "/home/codio/workspace/blango/blog/templatetags/blog_extras.py", line 55, in recent_posts
    posts = cache.get_or_set(f"recent_posts_exclude_post_{post.pk}", get_recent_post(post))
NameError: name 'cache' is not defined
INFO 10/08/23 08:33 autoreload 262 140240208164672 Watching for file changes with StatReloader
ERROR 10/08/23 08:33 log 262 140240096569088 Internal Server Error: /post/my-example-post
Traceback (most recent call last):
  File "/home/codio/.local/lib/python3.6/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/codio/.local/lib/python3.6/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/codio/workspace/blango/blog/views.py", line 35, in post_detail
    "comment_form": comment_form})
  File "/home/codio/.local/lib/python3.6/site-packages/django/shortcuts.py", line 19, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/home/codio/.local/lib/python3.6/site-packages/django/template/loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "/home/codio/.local/lib/python3.6/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/home/codio/.local/lib/python3.6/site-packages/django/template/base.py", line 170, in render
    return self._render(context)
  File "/home/codio/.local/lib/python3.6/site-packages/django/template/base.py", line 162, in _render
    return self.nodelist.render(context)
  File "/home/codio/.local/lib/python3.6/site-packages/django/template/base.py", line 938, in render
    bit = node.render_annotated(context)
  File "/home/codio/.local/lib/python3.6/site-packages/django/template/base.py", line 905, in render_annotated
    return self.render(context)
  File "/home/codio/.local/lib/python3.6/site-packages/django/template/loader_tags.py", line 150, in render
    return compiled_parent._render(context)
  File "/home/codio/.local/lib/python3.6/site-packages/django/template/base.py", line 162, in _render
    return self.nodelist.render(context)
  File "/home/codio/.local/lib/python3.6/site-packages/django/template/base.py", line 938, in render
    bit = node.render_annotated(context)
  File "/home/codio/.local/lib/python3.6/site-packages/django/template/base.py", line 905, in render_annotated
    return self.render(context)
  File "/home/codio/.local/lib/python3.6/site-packages/django/template/loader_tags.py", line 62, in render
    result = block.nodelist.render(context)
  File "/home/codio/.local/lib/python3.6/site-packages/django/template/base.py", line 938, in render
    bit = node.render_annotated(context)
  File "/home/codio/.local/lib/python3.6/site-packages/django/template/base.py", line 905, in render_annotated
    return self.render(context)
  File "/home/codio/.local/lib/python3.6/site-packages/django/templatetags/cache.py", line 47, in render
    value = self.nodelist.render(context)
  File "/home/codio/.local/lib/python3.6/site-packages/django/template/base.py", line 938, in render
    bit = node.render_annotated(context)
  File "/home/codio/.local/lib/python3.6/site-packages/django/template/base.py", line 905, in render_annotated
    return self.render(context)
  File "/home/codio/.local/lib/python3.6/site-packages/django/template/library.py", line 214, in render
    _dict = self.func(*resolved_args, **resolved_kwargs)
  File "/home/codio/workspace/blango/blog/templatetags/blog_extras.py", line 56, in recent_posts
    posts = cache.get_or_set(f"recent_posts_exclude_post_{post.pk}", get_recent_post(post))
NameError: name 'get_recent_post' is not defined
INFO 10/08/23 08:33 autoreload 262 140240208164672 /home/codio/workspace/blango/blog/templatetags/blog_extras.py changed, reloading.
INFO 10/08/23 08:33 autoreload 267 139661105739584 Watching for file changes with StatReloader
ERROR 10/08/23 08:33 log 267 139660925748992 Internal Server Error: /post/my-example-post
Traceback (most recent call last):
  File "/home/codio/.local/lib/python3.6/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/codio/.local/lib/python3.6/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/codio/workspace/blango/blog/views.py", line 35, in post_detail
    "comment_form": comment_form})
  File "/home/codio/.local/lib/python3.6/site-packages/django/shortcuts.py", line 19, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/home/codio/.local/lib/python3.6/site-packages/django/template/loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "/home/codio/.local/lib/python3.6/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/home/codio/.local/lib/python3.6/site-packages/django/template/base.py", line 170, in render
    return self._render(context)
  File "/home/codio/.local/lib/python3.6/site-packages/django/template/base.py", line 162, in _render
    return self.nodelist.render(context)
  File "/home/codio/.local/lib/python3.6/site-packages/django/template/base.py", line 938, in render
    bit = node.render_annotated(context)
  File "/home/codio/.local/lib/python3.6/site-packages/django/template/base.py", line 905, in render_annotated
    return self.render(context)
  File "/home/codio/.local/lib/python3.6/site-packages/django/template/loader_tags.py", line 150, in render
    return compiled_parent._render(context)
  File "/home/codio/.local/lib/python3.6/site-packages/django/template/base.py", line 162, in _render
    return self.nodelist.render(context)
  File "/home/codio/.local/lib/python3.6/site-packages/django/template/base.py", line 938, in render
    bit = node.render_annotated(context)
  File "/home/codio/.local/lib/python3.6/site-packages/django/template/base.py", line 905, in render_annotated
    return self.render(context)
  File "/home/codio/.local/lib/python3.6/site-packages/django/template/loader_tags.py", line 62, in render
    result = block.nodelist.render(context)
  File "/home/codio/.local/lib/python3.6/site-packages/django/template/base.py", line 938, in render
    bit = node.render_annotated(context)
  File "/home/codio/.local/lib/python3.6/site-packages/django/template/base.py", line 905, in render_annotated
    return self.render(context)
  File "/home/codio/.local/lib/python3.6/site-packages/django/templatetags/cache.py", line 47, in render
    value = self.nodelist.render(context)
  File "/home/codio/.local/lib/python3.6/site-packages/django/template/base.py", line 938, in render
    bit = node.render_annotated(context)
  File "/home/codio/.local/lib/python3.6/site-packages/django/template/base.py", line 905, in render_annotated
    return self.render(context)
  File "/home/codio/.local/lib/python3.6/site-packages/django/template/library.py", line 214, in render
    _dict = self.func(*resolved_args, **resolved_kwargs)
  File "/home/codio/workspace/blango/blog/templatetags/blog_extras.py", line 56, in recent_posts
    posts = cache.get_or_set(f"recent_posts_exclude_post_{post.pk}", get_recent_posts(post))
  File "/home/codio/workspace/blango/blog/templatetags/blog_extras.py", line 50, in get_recent_posts
    logger.debug(f"Loaded {len(posts)} recent post for post {post}")
NameError: name 'posts' is not defined
ERROR 10/08/23 08:33 log 267 139660925748992 Internal Server Error: /post/my-example-post
Traceback (most recent call last):
  File "/home/codio/.local/lib/python3.6/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/codio/.local/lib/python3.6/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/codio/workspace/blango/blog/views.py", line 35, in post_detail
    "comment_form": comment_form})
  File "/home/codio/.local/lib/python3.6/site-packages/django/shortcuts.py", line 19, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/home/codio/.local/lib/python3.6/site-packages/django/template/loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "/home/codio/.local/lib/python3.6/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/home/codio/.local/lib/python3.6/site-packages/django/template/base.py", line 170, in render
    return self._render(context)
  File "/home/codio/.local/lib/python3.6/site-packages/django/template/base.py", line 162, in _render
    return self.nodelist.render(context)
  File "/home/codio/.local/lib/python3.6/site-packages/django/template/base.py", line 938, in render
    bit = node.render_annotated(context)
  File "/home/codio/.local/lib/python3.6/site-packages/django/template/base.py", line 905, in render_annotated
    return self.render(context)
  File "/home/codio/.local/lib/python3.6/site-packages/django/template/loader_tags.py", line 150, in render
    return compiled_parent._render(context)
  File "/home/codio/.local/lib/python3.6/site-packages/django/template/base.py", line 162, in _render
    return self.nodelist.render(context)
  File "/home/codio/.local/lib/python3.6/site-packages/django/template/base.py", line 938, in render
    bit = node.render_annotated(context)
  File "/home/codio/.local/lib/python3.6/site-packages/django/template/base.py", line 905, in render_annotated
    return self.render(context)
  File "/home/codio/.local/lib/python3.6/site-packages/django/template/loader_tags.py", line 62, in render
    result = block.nodelist.render(context)
  File "/home/codio/.local/lib/python3.6/site-packages/django/template/base.py", line 938, in render
    bit = node.render_annotated(context)
  File "/home/codio/.local/lib/python3.6/site-packages/django/template/base.py", line 905, in render_annotated
    return self.render(context)
  File "/home/codio/.local/lib/python3.6/site-packages/django/templatetags/cache.py", line 47, in render
    value = self.nodelist.render(context)
  File "/home/codio/.local/lib/python3.6/site-packages/django/template/base.py", line 938, in render
    bit = node.render_annotated(context)
  File "/home/codio/.local/lib/python3.6/site-packages/django/template/base.py", line 905, in render_annotated
    return self.render(context)
  File "/home/codio/.local/lib/python3.6/site-packages/django/template/library.py", line 214, in render
    _dict = self.func(*resolved_args, **resolved_kwargs)
  File "/home/codio/workspace/blango/blog/templatetags/blog_extras.py", line 56, in recent_posts
    posts = cache.get_or_set(f"recent_posts_exclude_post_{post.pk}", get_recent_posts(post))
  File "/home/codio/workspace/blango/blog/templatetags/blog_extras.py", line 50, in get_recent_posts
    logger.debug(f"Loaded {len(posts)} recent post for post {post}")
NameError: name 'posts' is not defined
ERROR 10/08/23 08:33 log 267 139660925748992 Internal Server Error: /post/my-example-post
Traceback (most recent call last):
  File "/home/codio/.local/lib/python3.6/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/codio/.local/lib/python3.6/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/codio/workspace/blango/blog/views.py", line 35, in post_detail
    "comment_form": comment_form})
  File "/home/codio/.local/lib/python3.6/site-packages/django/shortcuts.py", line 19, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/home/codio/.local/lib/python3.6/site-packages/django/template/loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "/home/codio/.local/lib/python3.6/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/home/codio/.local/lib/python3.6/site-packages/django/template/base.py", line 170, in render
    return self._render(context)
  File "/home/codio/.local/lib/python3.6/site-packages/django/template/base.py", line 162, in _render
    return self.nodelist.render(context)
  File "/home/codio/.local/lib/python3.6/site-packages/django/template/base.py", line 938, in render
    bit = node.render_annotated(context)
  File "/home/codio/.local/lib/python3.6/site-packages/django/template/base.py", line 905, in render_annotated
    return self.render(context)
  File "/home/codio/.local/lib/python3.6/site-packages/django/template/loader_tags.py", line 150, in render
    return compiled_parent._render(context)
  File "/home/codio/.local/lib/python3.6/site-packages/django/template/base.py", line 162, in _render
    return self.nodelist.render(context)
  File "/home/codio/.local/lib/python3.6/site-packages/django/template/base.py", line 938, in render
    bit = node.render_annotated(context)
  File "/home/codio/.local/lib/python3.6/site-packages/django/template/base.py", line 905, in render_annotated
    return self.render(context)
  File "/home/codio/.local/lib/python3.6/site-packages/django/template/loader_tags.py", line 62, in render
    result = block.nodelist.render(context)
  File "/home/codio/.local/lib/python3.6/site-packages/django/template/base.py", line 938, in render
    bit = node.render_annotated(context)
  File "/home/codio/.local/lib/python3.6/site-packages/django/template/base.py", line 905, in render_annotated
    return self.render(context)
  File "/home/codio/.local/lib/python3.6/site-packages/django/templatetags/cache.py", line 47, in render
    value = self.nodelist.render(context)
  File "/home/codio/.local/lib/python3.6/site-packages/django/template/base.py", line 938, in render
    bit = node.render_annotated(context)
  File "/home/codio/.local/lib/python3.6/site-packages/django/template/base.py", line 905, in render_annotated
    return self.render(context)
  File "/home/codio/.local/lib/python3.6/site-packages/django/template/library.py", line 214, in render
    _dict = self.func(*resolved_args, **resolved_kwargs)
  File "/home/codio/workspace/blango/blog/templatetags/blog_extras.py", line 56, in recent_posts
    posts = cache.get_or_set(f"recent_posts_exclude_post_{post.pk}", get_recent_posts(post))
  File "/home/codio/workspace/blango/blog/templatetags/blog_extras.py", line 50, in get_recent_posts
    logger.debug(f"Loaded {len(posts)} recent post for post {post}")
NameError: name 'posts' is not defined
INFO 10/08/23 08:35 autoreload 267 139661105739584 /home/codio/workspace/blango/blog/templatetags/blog_extras.py changed, reloading.
INFO 10/08/23 08:35 autoreload 275 140014579464000 Watching for file changes with StatReloader
ERROR 10/08/23 08:35 log 275 140014468392704 Internal Server Error: /post/my-example-post
Traceback (most recent call last):
  File "/home/codio/.local/lib/python3.6/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/codio/.local/lib/python3.6/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/codio/workspace/blango/blog/views.py", line 35, in post_detail
    "comment_form": comment_form})
  File "/home/codio/.local/lib/python3.6/site-packages/django/shortcuts.py", line 19, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/home/codio/.local/lib/python3.6/site-packages/django/template/loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "/home/codio/.local/lib/python3.6/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/home/codio/.local/lib/python3.6/site-packages/django/template/base.py", line 170, in render
    return self._render(context)
  File "/home/codio/.local/lib/python3.6/site-packages/django/template/base.py", line 162, in _render
    return self.nodelist.render(context)
  File "/home/codio/.local/lib/python3.6/site-packages/django/template/base.py", line 938, in render
    bit = node.render_annotated(context)
  File "/home/codio/.local/lib/python3.6/site-packages/django/template/base.py", line 905, in render_annotated
    return self.render(context)
  File "/home/codio/.local/lib/python3.6/site-packages/django/template/loader_tags.py", line 150, in render
    return compiled_parent._render(context)
  File "/home/codio/.local/lib/python3.6/site-packages/django/template/base.py", line 162, in _render
    return self.nodelist.render(context)
  File "/home/codio/.local/lib/python3.6/site-packages/django/template/base.py", line 938, in render
    bit = node.render_annotated(context)
  File "/home/codio/.local/lib/python3.6/site-packages/django/template/base.py", line 905, in render_annotated
    return self.render(context)
  File "/home/codio/.local/lib/python3.6/site-packages/django/template/loader_tags.py", line 62, in render
    result = block.nodelist.render(context)
  File "/home/codio/.local/lib/python3.6/site-packages/django/template/base.py", line 938, in render
    bit = node.render_annotated(context)
  File "/home/codio/.local/lib/python3.6/site-packages/django/template/base.py", line 905, in render_annotated
    return self.render(context)
  File "/home/codio/.local/lib/python3.6/site-packages/django/templatetags/cache.py", line 47, in render
    value = self.nodelist.render(context)
  File "/home/codio/.local/lib/python3.6/site-packages/django/template/base.py", line 938, in render
    bit = node.render_annotated(context)
  File "/home/codio/.local/lib/python3.6/site-packages/django/template/base.py", line 905, in render_annotated
    return self.render(context)
  File "/home/codio/.local/lib/python3.6/site-packages/django/template/library.py", line 214, in render
    _dict = self.func(*resolved_args, **resolved_kwargs)
  File "/home/codio/workspace/blango/blog/templatetags/blog_extras.py", line 56, in recent_posts
    posts = cache.get_or_set(f"recent_posts_exclude_post_{post.pk}", get_recent_posts)
  File "/home/codio/.local/lib/python3.6/site-packages/django/core/cache/backends/base.py", line 173, in get_or_set
    default = default()
TypeError: get_recent_posts() missing 1 required positional argument: 'post'
INFO 10/08/23 08:36 autoreload 275 140014579464000 /home/codio/workspace/blango/blog/templatetags/blog_extras.py changed, reloading.
INFO 10/08/23 08:36 autoreload 280 140214217578304 Watching for file changes with StatReloader
INFO 10/08/23 08:36 autoreload 280 140214217578304 /home/codio/workspace/blango/blog/templatetags/blog_extras.py changed, reloading.
INFO 10/08/23 08:36 autoreload 283 139756344166208 Watching for file changes with StatReloader
ERROR 10/08/23 08:36 log 283 139756233094912 Internal Server Error: /post/my-example-post
Traceback (most recent call last):
  File "/home/codio/.local/lib/python3.6/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/codio/.local/lib/python3.6/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/codio/workspace/blango/blog/views.py", line 35, in post_detail
    "comment_form": comment_form})
  File "/home/codio/.local/lib/python3.6/site-packages/django/shortcuts.py", line 19, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/home/codio/.local/lib/python3.6/site-packages/django/template/loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "/home/codio/.local/lib/python3.6/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/home/codio/.local/lib/python3.6/site-packages/django/template/base.py", line 170, in render
    return self._render(context)
  File "/home/codio/.local/lib/python3.6/site-packages/django/template/base.py", line 162, in _render
    return self.nodelist.render(context)
  File "/home/codio/.local/lib/python3.6/site-packages/django/template/base.py", line 938, in render
    bit = node.render_annotated(context)
  File "/home/codio/.local/lib/python3.6/site-packages/django/template/base.py", line 905, in render_annotated
    return self.render(context)
  File "/home/codio/.local/lib/python3.6/site-packages/django/template/loader_tags.py", line 150, in render
    return compiled_parent._render(context)
  File "/home/codio/.local/lib/python3.6/site-packages/django/template/base.py", line 162, in _render
    return self.nodelist.render(context)
  File "/home/codio/.local/lib/python3.6/site-packages/django/template/base.py", line 938, in render
    bit = node.render_annotated(context)
  File "/home/codio/.local/lib/python3.6/site-packages/django/template/base.py", line 905, in render_annotated
    return self.render(context)
  File "/home/codio/.local/lib/python3.6/site-packages/django/template/loader_tags.py", line 62, in render
    result = block.nodelist.render(context)
  File "/home/codio/.local/lib/python3.6/site-packages/django/template/base.py", line 938, in render
    bit = node.render_annotated(context)
  File "/home/codio/.local/lib/python3.6/site-packages/django/template/base.py", line 905, in render_annotated
    return self.render(context)
  File "/home/codio/.local/lib/python3.6/site-packages/django/templatetags/cache.py", line 47, in render
    value = self.nodelist.render(context)
  File "/home/codio/.local/lib/python3.6/site-packages/django/template/base.py", line 938, in render
    bit = node.render_annotated(context)
  File "/home/codio/.local/lib/python3.6/site-packages/django/template/base.py", line 905, in render_annotated
    return self.render(context)
  File "/home/codio/.local/lib/python3.6/site-packages/django/template/library.py", line 214, in render
    _dict = self.func(*resolved_args, **resolved_kwargs)
  File "/home/codio/workspace/blango/blog/templatetags/blog_extras.py", line 56, in recent_posts
    posts = cache.get_or_set(f"recent_posts_exclude_post_{post.pk}", get_recent_posts(post))
  File "/home/codio/workspace/blango/blog/templatetags/blog_extras.py", line 50, in get_recent_posts
    logger.debug(f"Loaded {len(posts)} recent post for post {post}")
NameError: name 'posts' is not defined
INFO 10/08/23 08:36 autoreload 283 139756344166208 /home/codio/workspace/blango/blog/templatetags/blog_extras.py changed, reloading.
INFO 10/08/23 08:36 autoreload 287 140290343499584 Watching for file changes with StatReloader
INFO 10/08/23 08:36 autoreload 287 140290343499584 /home/codio/workspace/blango/blog/templatetags/blog_extras.py changed, reloading.
INFO 10/08/23 08:36 autoreload 290 140709119215424 Watching for file changes with StatReloader
INFO 10/08/23 08:58 autoreload 361 140576103905088 Watching for file changes with StatReloader
INFO 10/08/23 09:05 autoreload 380 140193355310912 Watching for file changes with StatReloader
INFO 10/08/23 09:07 autoreload 380 140193355310912 /home/codio/workspace/blango/blango/settings.py changed, reloading.
INFO 10/08/23 09:07 autoreload 406 139804994332480 Watching for file changes with StatReloader
INFO 10/08/23 09:08 autoreload 406 139804994332480 /home/codio/workspace/blango/blango/settings.py changed, reloading.
INFO 10/08/23 09:08 autoreload 410 139779861088064 Watching for file changes with StatReloader
INFO 10/08/23 09:08 autoreload 465 139938305554240 Watching for file changes with StatReloader
INFO 10/08/23 09:45 autoreload 507 140219585677120 Watching for file changes with StatReloader
INFO 10/08/23 09:47 autoreload 507 140219585677120 /home/codio/workspace/blango/blog/models.py changed, reloading.
INFO 10/08/23 09:47 autoreload 522 139905957128000 Watching for file changes with StatReloader
INFO 10/08/23 09:47 autoreload 531 140212542461760 Watching for file changes with StatReloader
INFO 13/08/23 11:04 autoreload 282 140331642382144 Watching for file changes with StatReloader
INFO 13/08/23 11:07 autoreload 364 140698727032640 Watching for file changes with StatReloader
INFO 13/08/23 11:07 autoreload 371 140106812680000 Watching for file changes with StatReloader
INFO 13/08/23 11:08 autoreload 446 140677495375680 Watching for file changes with StatReloader
INFO 13/08/23 11:12 autoreload 508 140525094184768 Watching for file changes with StatReloader
INFO 13/08/23 11:15 autoreload 573 140361400944448 Watching for file changes with StatReloader
INFO 13/08/23 11:15 autoreload 583 139659471316800 Watching for file changes with StatReloader
INFO 13/08/23 11:31 autoreload 1082 139752773261120 Watching for file changes with StatReloader
INFO 13/08/23 11:34 autoreload 1082 139752773261120 /home/codio/workspace/blango/blog/views.py changed, reloading.
INFO 13/08/23 11:34 autoreload 1097 140179986208576 Watching for file changes with StatReloader
INFO 13/08/23 11:38 autoreload 1097 140179986208576 /home/codio/workspace/blango/blog/views.py changed, reloading.
INFO 13/08/23 11:38 autoreload 1104 139734853244736 Watching for file changes with StatReloader
INFO 13/08/23 11:40 autoreload 1104 139734853244736 /home/codio/workspace/blango/blog/views.py changed, reloading.
INFO 13/08/23 11:40 autoreload 1113 140129914754880 Watching for file changes with StatReloader
INFO 13/08/23 11:40 autoreload 1113 140129914754880 /home/codio/workspace/blango/blog/views.py changed, reloading.
INFO 13/08/23 11:40 autoreload 1118 140402428270400 Watching for file changes with StatReloader
INFO 13/08/23 11:40 autoreload 1118 140402428270400 /home/codio/workspace/blango/blog/views.py changed, reloading.
INFO 13/08/23 11:40 autoreload 1121 140217862743872 Watching for file changes with StatReloader
INFO 13/08/23 11:41 autoreload 1121 140217862743872 /home/codio/workspace/blango/blog/views.py changed, reloading.
INFO 13/08/23 11:41 autoreload 1126 140633449162560 Watching for file changes with StatReloader
INFO 13/08/23 11:41 autoreload 1126 140633449162560 /home/codio/workspace/blango/blog/views.py changed, reloading.
INFO 13/08/23 11:41 autoreload 1131 140556679923520 Watching for file changes with StatReloader
INFO 13/08/23 11:41 autoreload 1131 140556679923520 /home/codio/workspace/blango/blog/views.py changed, reloading.
INFO 13/08/23 11:42 autoreload 1138 139763929651008 Watching for file changes with StatReloader
ERROR 13/08/23 11:42 log 1138 139763738736384 Internal Server Error: /
Traceback (most recent call last):
  File "/home/codio/.local/lib/python3.6/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/codio/.local/lib/python3.6/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/codio/workspace/blango/blog/views.py", line 22, in index
    logger.debug(f"Got %d posts", len(posts))
  File "/home/codio/.local/lib/python3.6/site-packages/django/db/models/query.py", line 262, in __len__
    self._fetch_all()
  File "/home/codio/.local/lib/python3.6/site-packages/django/db/models/query.py", line 1324, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "/home/codio/.local/lib/python3.6/site-packages/django/db/models/query.py", line 51, in __iter__
    results = compiler.execute_sql(chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size)
  File "/home/codio/.local/lib/python3.6/site-packages/django/db/models/sql/compiler.py", line 1162, in execute_sql
    sql, params = self.as_sql()
  File "/home/codio/.local/lib/python3.6/site-packages/django/db/models/sql/compiler.py", line 513, in as_sql
    extra_select, order_by, group_by = self.pre_sql_setup()
  File "/home/codio/.local/lib/python3.6/site-packages/django/db/models/sql/compiler.py", line 55, in pre_sql_setup
    self.setup_query()
  File "/home/codio/.local/lib/python3.6/site-packages/django/db/models/sql/compiler.py", line 46, in setup_query
    self.select, self.klass_info, self.annotation_col_map = self.get_select()
  File "/home/codio/.local/lib/python3.6/site-packages/django/db/models/sql/compiler.py", line 248, in get_select
    related_klass_infos = self.get_related_selections(select)
  File "/home/codio/.local/lib/python3.6/site-packages/django/db/models/sql/compiler.py", line 876, in get_related_selections
    only_load.get(field_model)):
  File "/home/codio/.local/lib/python3.6/site-packages/django/db/models/query_utils.py", line 262, in select_related_descend
    raise FieldError(msg)
django.core.exceptions.FieldError: Field Post.author cannot be both deferred and traversed using select_related at the same time.
INFO 13/08/23 11:42 autoreload 1138 139763929651008 /home/codio/workspace/blango/blog/views.py changed, reloading.
INFO 13/08/23 11:42 autoreload 1142 140238963660608 Watching for file changes with StatReloader
INFO 13/08/23 11:42 autoreload 1142 140238963660608 /home/codio/workspace/blango/blog/views.py changed, reloading.
INFO 13/08/23 11:42 autoreload 1147 140200483854144 Watching for file changes with StatReloader
ERROR 13/08/23 11:42 log 1147 140200366716672 Internal Server Error: /
Traceback (most recent call last):
  File "/home/codio/.local/lib/python3.6/site-packages/django/db/models/options.py", line 608, in get_field
    return self.fields_map[field_name]
KeyError: 'object_id'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/codio/.local/lib/python3.6/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/codio/.local/lib/python3.6/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/codio/workspace/blango/blog/views.py", line 22, in index
    logger.debug(f"Got %d posts", len(posts))
  File "/home/codio/.local/lib/python3.6/site-packages/django/db/models/query.py", line 262, in __len__
    self._fetch_all()
  File "/home/codio/.local/lib/python3.6/site-packages/django/db/models/query.py", line 1324, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "/home/codio/.local/lib/python3.6/site-packages/django/db/models/query.py", line 51, in __iter__
    results = compiler.execute_sql(chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size)
  File "/home/codio/.local/lib/python3.6/site-packages/django/db/models/sql/compiler.py", line 1162, in execute_sql
    sql, params = self.as_sql()
  File "/home/codio/.local/lib/python3.6/site-packages/django/db/models/sql/compiler.py", line 513, in as_sql
    extra_select, order_by, group_by = self.pre_sql_setup()
  File "/home/codio/.local/lib/python3.6/site-packages/django/db/models/sql/compiler.py", line 55, in pre_sql_setup
    self.setup_query()
  File "/home/codio/.local/lib/python3.6/site-packages/django/db/models/sql/compiler.py", line 46, in setup_query
    self.select, self.klass_info, self.annotation_col_map = self.get_select()
  File "/home/codio/.local/lib/python3.6/site-packages/django/db/models/sql/compiler.py", line 227, in get_select
    cols = self.get_default_columns()
  File "/home/codio/.local/lib/python3.6/site-packages/django/db/models/sql/compiler.py", line 677, in get_default_columns
    only_load = self.deferred_to_columns()
  File "/home/codio/.local/lib/python3.6/site-packages/django/db/models/sql/compiler.py", line 1102, in deferred_to_columns
    self.query.deferred_to_data(columns, self.query.get_loaded_field_names_cb)
  File "/home/codio/.local/lib/python3.6/site-packages/django/db/models/sql/query.py", line 722, in deferred_to_data
    field = opts.get_field(parts[-1])
  File "/home/codio/.local/lib/python3.6/site-packages/django/db/models/options.py", line 610, in get_field
    raise FieldDoesNotExist("%s has no field named '%s'" % (self.object_name, field_name))
django.core.exceptions.FieldDoesNotExist: Post has no field named 'object_id'
INFO 13/08/23 11:43 autoreload 1147 140200483854144 /home/codio/workspace/blango/blog/views.py changed, reloading.
INFO 13/08/23 11:43 autoreload 1151 140058036533056 Watching for file changes with StatReloader
INFO 13/08/23 11:43 autoreload 1151 140058036533056 /home/codio/workspace/blango/blog/views.py changed, reloading.
INFO 13/08/23 11:43 autoreload 1154 140618580744000 Watching for file changes with StatReloader
INFO 13/08/23 11:43 autoreload 1154 140618580744000 /home/codio/workspace/blango/blog/views.py changed, reloading.
INFO 13/08/23 11:43 autoreload 1159 140252395542336 Watching for file changes with StatReloader
INFO 13/08/23 11:44 autoreload 1159 140252395542336 /home/codio/workspace/blango/blog/views.py changed, reloading.
INFO 13/08/23 11:44 autoreload 1164 140040698619712 Watching for file changes with StatReloader
INFO 13/08/23 11:44 autoreload 1164 140040698619712 /home/codio/workspace/blango/blog/views.py changed, reloading.
INFO 13/08/23 11:44 autoreload 1171 140480354252608 Watching for file changes with StatReloader
INFO 13/08/23 11:44 autoreload 1171 140480354252608 /home/codio/workspace/blango/blog/views.py changed, reloading.
INFO 13/08/23 11:44 autoreload 1176 140506852464448 Watching for file changes with StatReloader
INFO 13/08/23 11:45 autoreload 1176 140506852464448 /home/codio/workspace/blango/blog/views.py changed, reloading.
INFO 13/08/23 11:45 autoreload 1181 139883273537344 Watching for file changes with StatReloader
INFO 13/08/23 11:45 autoreload 1181 139883273537344 /home/codio/workspace/blango/blog/views.py changed, reloading.
INFO 13/08/23 11:45 autoreload 1187 140358132520768 Watching for file changes with StatReloader
INFO 13/08/23 11:45 autoreload 1187 140358132520768 /home/codio/workspace/blango/blog/views.py changed, reloading.
INFO 13/08/23 11:45 autoreload 1192 139837105788736 Watching for file changes with StatReloader
INFO 13/08/23 11:46 autoreload 1192 139837105788736 /home/codio/workspace/blango/blog/views.py changed, reloading.
INFO 13/08/23 11:46 autoreload 1197 140035474024256 Watching for file changes with StatReloader
INFO 13/08/23 11:46 autoreload 1197 140035474024256 /home/codio/workspace/blango/blog/views.py changed, reloading.
INFO 13/08/23 11:46 autoreload 1202 140265898100544 Watching for file changes with StatReloader
INFO 13/08/23 11:47 autoreload 1202 140265898100544 /home/codio/workspace/blango/blog/views.py changed, reloading.
INFO 13/08/23 11:47 autoreload 1210 139961911678784 Watching for file changes with StatReloader
INFO 16/08/23 20:01 autoreload 787 140665928136512 Watching for file changes with StatReloader
INFO 16/08/23 20:14 autoreload 950 140716998428480 Watching for file changes with StatReloader
INFO 16/08/23 21:26 autoreload 1033 140504683980608 Watching for file changes with StatReloader
INFO 16/08/23 21:26 autoreload 1038 140104383510336 Watching for file changes with StatReloader
INFO 16/08/23 21:26 autoreload 1043 139916292724544 Watching for file changes with StatReloader
INFO 17/08/23 10:04 autoreload 601 140329063700288 Watching for file changes with StatReloader
INFO 17/08/23 10:07 autoreload 714 139774054393664 Watching for file changes with StatReloader
INFO 17/08/23 11:18 autoreload 1589 140093451552576 Watching for file changes with StatReloader
INFO 20/08/23 08:36 autoreload 393 140580155279168 Watching for file changes with StatReloader
ERROR 20/08/23 08:39 log 393 140579849631488 Internal Server Error: /accounts/google/login/
Traceback (most recent call last):
  File "/home/codio/.local/lib/python3.6/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/codio/.local/lib/python3.6/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/codio/.local/lib/python3.6/site-packages/allauth/socialaccount/providers/oauth2/views.py", line 77, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/codio/.local/lib/python3.6/site-packages/allauth/socialaccount/providers/oauth2/views.py", line 105, in dispatch
    app = provider.get_app(self.request)
  File "/home/codio/.local/lib/python3.6/site-packages/allauth/socialaccount/providers/base.py", line 49, in get_app
    return adapter.get_app(request, self.id)
  File "/home/codio/.local/lib/python3.6/site-packages/allauth/socialaccount/adapter.py", line 204, in get_app
    app = SocialApp.objects.get_current(provider, request)
  File "/home/codio/.local/lib/python3.6/site-packages/allauth/socialaccount/models.py", line 32, in get_current
    app = self.get(sites__id=site.id, provider=provider)
  File "/home/codio/.local/lib/python3.6/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/codio/.local/lib/python3.6/site-packages/django/db/models/query.py", line 437, in get
    self.model._meta.object_name
allauth.socialaccount.models.SocialApp.DoesNotExist: SocialApp matching query does not exist.
INFO 20/08/23 08:41 views 393 140579849631488 Created a comment on post 1 from user z9661744@gmail.com
